# Generated by Django 4.1.8 on 2023-04-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ebook", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
