# Generated by Django 4.1.8 on 2023-04-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ebook", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="from_email",
            new_name="company_name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="to_email",
            new_name="email",
        ),
    ]
